version: '3.8'

name: omnicore-core-dev


services:
  core-library-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_PROFILE: dev
    container_name: omnicore-core-dev-build
    profiles:
      - build-only
